Proj2: person.o student.o teacher.o course.o test.o
	g++ person.o student.o teacher.o course.o test.o -o Proj2
person.o:
	g++ -c person.cpp
student.o:
	g++ -c student.cpp
teacher.o:
	g++ -c teacher.cpp
course.o:
	g++ -c course.cpp
test.o:
	g++ -c test.cpp