python3 -c "from tests0 import testPrime; testPrime(1, False)"
python3 -c "from tests0 import testPrime; testPrime(2, True)"
python3 -c "from tests0 import testPrime; testPrime(8, False)"
python3 -c "from tests0 import testPrime; testPrime(11, True)"
python3 -c "from tests0 import testPrime; testPrime(25, False)"
python3 -c "from tests0 import testPrime; testPrime(28, False)"
