--Honors Hands-On Lab: Joins
--Problem 1: List the case number, type of crime and community area for all crimes in community area number 18.
SELECT CRM.CASE_NUMBER, CRM.PRIMARY_TYPE, CEN.COMMUNITY_AREA_NAME
FROM CHICAGO_CRIME_DATA CRM INNER JOIN CENSUS_DATA CEN 
ON CRM.COMMUNITY_AREA_NUMBER = CEN.COMMUNITY_AREA_NUMBER
WHERE CEN.COMMUNITY_AREA_NUMBER = 18;

--Problem 2: List all crimes that took place at a school. Include case number, crime type and community name.
SELECT CRM.CASE_NUMBER, CRM.PRIMARY_TYPE, CEN.COMMUNITY_AREA_NAME
FROM CHICAGO_CRIME_DATA CRM LEFT JOIN CENSUS_DATA CEN 
ON CRM.COMMUNITY_AREA_NUMBER = CEN.COMMUNITY_AREA_NUMBER
WHERE CRM.LOCATION_DESCRIPTION LIKE '%SCHOOL%';

--Problem 3: For the communities of Oakland, Armour Square, Edgewater and CHICAGO list the associated community_area_numbers and the case_numbers.
SELECT CEN.COMMUNITY_AREA_NAME, CEN.COMMUNITY_AREA_NUMBER, CRM.CASE_NUMBER
FROM CENSUS_DATA CEN FULL JOIN CHICAGO_CRIME_DATA CRM 
ON CEN.COMMUNITY_AREA_NUMBER = CEN.COMMUNITY_AREA_NUMBER 
WHERE CEN.COMMUNITY_AREA_NAME = 'Oakland' 
OR CEN.COMMUNITY_AREA_NAME = 'Armour Square' 
OR CEN.COMMUNITY_AREA_NAME = 'Edgewater'
OR CEN.COMMUNITY_AREA_NAME = 'CHICAGO';