---Hands-On Lab: Using Views
---Exercise 1: Create a VIEW
--CREATE VIEW EMPSALARY AS 
--SELECT EMP_ID, F_NAME, L_NAME, B_DATE, SEX, SALARY FROM EMPLOYEES;

--Retrieving all of the records from the view:
SELECT * FROM EMPSALARY;


---Exercise 2: Updating a view 
CREATE OR REPLACE VIEW EMPSALARY AS 
SELECT EMP_ID, F_NAME, L_NAME, B_DATE, SEX, JOB_TITLE, MIN_SALARY, MAX_SALARY
FROM EMPLOYEES, JOBS 
WHERE EMPLOYEES.JOB_ID = JOBS.JOB_IDENT;

--Querying updated EMPSALARY:
SELECT * FROM EMPSALARY;

---Exercise 3: Dropping a view 
DROP VIEW EMPSALARY;
SELECT * FROM EMPSALARY;